/*
 * This file was generated by the Gradle 'init' task.
 */
import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id("buildlogic.kotlin-application-conventions")
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

group = "org.groovy_lsp"
version = "0.1.0"

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(kotlin("test"))
    implementation("org.apache.commons:commons-text")
    implementation("org.eclipse.lsp4j:org.eclipse.lsp4j:0.22.0")
    implementation("org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc:0.22.0")
    implementation(project(":lsp"))
}

application {
    // Define the main class for the application.
    mainClass.set("org.groovy_lsp.app.GroovyLanguageServerKt")
}

tasks {
    build {
        dependsOn(shadowJar)
    }
}

tasks.named<ShadowJar>("shadowJar") {
    manifest {
        attributes["Main-Class"] = "org.groovy_lsp.app.GroovyLanguageServerKt"
    }
}
