/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":lsp"))
}

application {
    // Define the main class for the application.
    mainClass = "org.groovy_lsp.app.ServerKt"
}
